import type { Config } from 'tailwindcss';

export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#0f131f',
        surface: '#0f131f',
        'surface-dim': '#0f131f',
        'surface-bright': '#353946',
        'surface-container-lowest': '#0a0e1a',
        'surface-container-low': '#171b28',
        'surface-container': '#1b1f2c',
        'surface-container-high': '#262a37',
        'surface-container-highest': '#313442',
        'surface-variant': '#313442',
        'on-surface': '#dfe2f3',
        'on-surface-variant': '#c5c5d3',
        'on-background': '#dfe2f3',
        outline: '#8f909c',
        'outline-variant': '#454651',
        primary: '#bbc6ff',
        'on-primary': '#0e2878',
        'primary-container': '#95a9ff',
        'on-primary-container': '#253b89',
        'primary-fixed': '#dde1ff',
        'primary-fixed-dim': '#b7c4ff',
        'on-primary-fixed': '#001453',
        'on-primary-fixed-variant': '#2b418f',
        secondary: '#d7fff3',
        'on-secondary': '#00382f',
        'secondary-container': '#00f5d3',
        'on-secondary-container': '#006c5c',
        'secondary-fixed': '#25fedc',
        'secondary-fixed-dim': '#00dfc0',
        'on-secondary-fixed': '#00201a',
        'on-secondary-fixed-variant': '#005144',
        tertiary: '#ffafed',
        'on-tertiary': '#56124f',
        'tertiary-container': '#e691d4',
        'on-tertiary-container': '#6a2561',
        'tertiary-fixed': '#ffd7f2',
        'tertiary-fixed-dim': '#ffacec',
        'on-tertiary-fixed': '#390035',
        'on-tertiary-fixed-variant': '#712b68',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'inverse-surface': '#dfe2f3',
        'inverse-on-surface': '#2c303d',
        'inverse-primary': '#4559a9',
        'surface-tint': '#b7c4ff',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '800' }],
        'headline-md': ['24px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'title-sm': ['16px', { lineHeight: '1.4', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-caps': ['10px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '800' }],
      },
    },
  },
  plugins: [],
} satisfies Config;
